import React, { useState } from 'react';
import { Sparkles, HelpCircle, BookOpen, AlertCircle, ShieldAlert, X, ArrowRight, Lock } from 'lucide-react';
import { useApp } from '../../context/AppContext';

interface AIGuidanceModalProps {
  isOpen: boolean;
  onClose: () => void;
  contextTitle?: string;
  contextDescription?: string;
}

export const AIGuidanceModal: React.FC<AIGuidanceModalProps> = ({ 
  isOpen, 
  onClose, 
  contextTitle = 'Shadow Problem: Fraud Detection Pipeline',
  contextDescription = 'Idempotent transaction deduplication under high load'
}) => {
  const { showToast } = useApp();
  const [selectedPromptType, setSelectedPromptType] = useState<'hint' | 'question' | 'explanation' | 'misconception' | 'resource'>('hint');
  const [userQuery, setUserQuery] = useState('');
  const [aiOutput, setAiOutput] = useState<{
    title: string;
    content: string;
    guidingQuestion?: string;
    suggestedDocs?: string[];
  } | null>({
    title: 'Architectural Eviction Strategy Hint',
    content: 'Consider how memory grows over time if keys are inserted without time-to-live boundaries. An in-memory hash map requires an explicit eviction policy (e.g. sliding window epoch comparison) or a bounded LRU cache data structure.',
    guidingQuestion: 'What is the time complexity of deleting expired keys during write operations versus running a periodic background eviction thread?',
    suggestedDocs: ['Python `collections.OrderedDict` API Docs', 'Redis Sorted Sets `ZREMRANGEBYSCORE` Pattern']
  });

  if (!isOpen) return null;

  const handleGenerateGuidance = (type: 'hint' | 'question' | 'explanation' | 'misconception' | 'resource') => {
    setSelectedPromptType(type);

    if (type === 'hint') {
      setAiOutput({
        title: 'Hint: Bounded Memory Eviction',
        content: 'Instead of storing all transaction IDs indefinitely, examine the maximum time window (5 minutes). Events older than 300 seconds are no longer risk duplicates and can be safely purged.',
        guidingQuestion: 'Can you implement a lazy cleanup inside your `is_duplicate` method that compares incoming `timestamp - stored_timestamp > 300`?',
        suggestedDocs: ['Sliding Window Rate Limiting Algorithms', 'Memory Footprint Benchmarking in Python']
      });
    } else if (type === 'question') {
      setAiOutput({
        title: 'Socratic Prompt: Edge-Case Latency',
        content: 'Suppose network packets arrive out of chronological order (e.g. event A with timestamp 10:00:05 arrives AFTER event B with timestamp 10:00:10).',
        guidingQuestion: 'How would your current deduplication logic handle an older event arriving after a newer event? Would it erroneously drop or duplicate it?',
        suggestedDocs: ['Handling Network Jitter in Distributed Stream Aggregators']
      });
    } else if (type === 'explanation') {
      setAiOutput({
        title: 'Concept Explanation: Idempotency Keys',
        content: 'An idempotency key is a unique token generated by the client per payload attempt. When the backend receives a request with an existing idempotency key, it returns the cached result without re-executing business logic or charging double balance.',
        guidingQuestion: 'Where in the processing pipeline should the idempotency check occur: before database persistence or after?',
        suggestedDocs: ['Stripe Idempotency API Specification', 'IETF HTTP Idempotency Key Draft']
      });
    } else if (type === 'misconception') {
      setAiOutput({
        title: 'Misconception Analysis: DB Joins vs Hot-Path Caching',
        content: 'Detected Pattern: Querying a relational database (`SELECT * FROM transactions WHERE hash = ?`) inside a 50,000 req/sec loop causes socket exhaustion and high latency spikes.',
        guidingQuestion: 'Why is an in-memory hash map or Redis cache mandatory for sub-millisecond hot-path deduplication before hitting relational storage?',
        suggestedDocs: ['High Throughput Hot-Path Architecture', 'Database Connection Pool Exhaustion']
      });
    } else if (type === 'resource') {
      setAiOutput({
        title: 'Curated Documentation & Learning Resources',
        content: 'Recommended foundational readings for mastering high-throughput event streaming & data structure optimization:',
        suggestedDocs: [
          'Designing Data-Intensive Applications — Chapter 11: Stream Processing',
          'Python memoryview and bytearray performance guides',
          'Apache Kafka Partition Key & Deduplication Patterns'
        ]
      });
    }

    showToast(`AI Guidance updated: ${type.toUpperCase()}`, 'info');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-mono-950/60 backdrop-blur-xs fade-in">
      <div className="w-full max-w-3xl bg-white border border-mono-300 rounded-lg shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="bg-mono-950 text-white p-4 border-b border-mono-800 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-md bg-mono-800 border border-mono-700 flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-mono-200" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-bold text-sm text-white">AI Guidance Engine</h3>
                <span className="text-[10px] font-mono bg-mono-800 text-mono-300 px-1.5 py-0.5 rounded border border-mono-700">
                  Strict Guardrails
                </span>
              </div>
              <p className="text-xs text-mono-400 font-mono">Context: {contextTitle}</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-1 text-mono-400 hover:text-white rounded-md transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Mandatory Tagline Banner */}
        <div className="bg-mono-100 border-b border-mono-200 px-4 py-2.5 flex items-center justify-between text-xs">
          <div className="flex items-center gap-2 font-extrabold text-mono-950 tracking-wider">
            <ShieldAlert className="w-4 h-4 text-mono-800" />
            <span>AI GUIDES. HUMANS SOLVE.</span>
          </div>
          <div className="flex items-center gap-1.5 text-mono-600 text-[11px]">
            <Lock className="w-3.5 h-3.5 text-mono-700" />
            <span>Final Code Generation Disabled by System Policy</span>
          </div>
        </div>

        {/* Content Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {/* Prompt Selector Buttons */}
          <div>
            <label className="block text-xs font-mono uppercase text-mono-500 font-semibold mb-2">
              Select Guidance Mode
            </label>
            <div className="grid grid-cols-2 sm:grid-cols-5 gap-2">
              <button
                onClick={() => handleGenerateGuidance('hint')}
                className={`px-3 py-2 text-xs font-semibold rounded-md border flex items-center justify-center gap-1.5 transition-all ${
                  selectedPromptType === 'hint'
                    ? 'bg-mono-950 text-white border-mono-950 shadow-xs'
                    : 'bg-mono-50 text-mono-700 border-mono-200 hover:bg-mono-100'
                }`}
              >
                <HelpCircle className="w-3.5 h-3.5" />
                <span>Hint</span>
              </button>

              <button
                onClick={() => handleGenerateGuidance('question')}
                className={`px-3 py-2 text-xs font-semibold rounded-md border flex items-center justify-center gap-1.5 transition-all ${
                  selectedPromptType === 'question'
                    ? 'bg-mono-950 text-white border-mono-950 shadow-xs'
                    : 'bg-mono-50 text-mono-700 border-mono-200 hover:bg-mono-100'
                }`}
              >
                <Sparkles className="w-3.5 h-3.5" />
                <span>Socratic</span>
              </button>

              <button
                onClick={() => handleGenerateGuidance('explanation')}
                className={`px-3 py-2 text-xs font-semibold rounded-md border flex items-center justify-center gap-1.5 transition-all ${
                  selectedPromptType === 'explanation'
                    ? 'bg-mono-950 text-white border-mono-950 shadow-xs'
                    : 'bg-mono-50 text-mono-700 border-mono-200 hover:bg-mono-100'
                }`}
              >
                <BookOpen className="w-3.5 h-3.5" />
                <span>Concept</span>
              </button>

              <button
                onClick={() => handleGenerateGuidance('misconception')}
                className={`px-3 py-2 text-xs font-semibold rounded-md border flex items-center justify-center gap-1.5 transition-all ${
                  selectedPromptType === 'misconception'
                    ? 'bg-mono-950 text-white border-mono-950 shadow-xs'
                    : 'bg-mono-50 text-mono-700 border-mono-200 hover:bg-mono-100'
                }`}
              >
                <AlertCircle className="w-3.5 h-3.5" />
                <span>Misconception</span>
              </button>

              <button
                onClick={() => handleGenerateGuidance('resource')}
                className={`px-3 py-2 text-xs font-semibold rounded-md border flex items-center justify-center gap-1.5 transition-all ${
                  selectedPromptType === 'resource'
                    ? 'bg-mono-950 text-white border-mono-950 shadow-xs'
                    : 'bg-mono-50 text-mono-700 border-mono-200 hover:bg-mono-100'
                }`}
              >
                <BookOpen className="w-3.5 h-3.5" />
                <span>Docs</span>
              </button>
            </div>
          </div>

          {/* Optional query input for custom contextual ask */}
          <div className="flex gap-2">
            <input 
              type="text"
              placeholder="Ask for clarification or conceptual advice (e.g., how to choose TTL vs LRU)..."
              value={userQuery}
              onChange={(e) => setUserQuery(e.target.value)}
              className="flex-1 px-3 py-2 text-xs border border-mono-300 rounded-md focus:outline-none focus:border-mono-900"
            />
            <button 
              onClick={() => handleGenerateGuidance(selectedPromptType)}
              className="px-4 py-2 bg-mono-900 hover:bg-mono-950 text-white text-xs font-semibold rounded-md transition-colors flex items-center gap-1"
            >
              <span>Ask AI</span>
              <ArrowRight className="w-3 h-3" />
            </button>
          </div>

          {/* AI Output Display Card */}
          {aiOutput && (
            <div className="border border-mono-300 rounded-lg p-5 bg-mono-50 space-y-4">
              <div className="flex items-center justify-between border-b border-mono-200 pb-3">
                <h4 className="font-bold text-sm text-mono-950 flex items-center gap-2">
                  <Sparkles className="w-4 h-4 text-mono-800" />
                  <span>{aiOutput.title}</span>
                </h4>
                <span className="text-[10px] font-mono bg-mono-200 text-mono-800 px-2 py-0.5 rounded uppercase font-semibold">
                  Guiding Feedback
                </span>
              </div>

              <p className="text-xs text-mono-800 leading-relaxed font-sans">
                {aiOutput.content}
              </p>

              {aiOutput.guidingQuestion && (
                <div className="p-3 bg-white border border-mono-300 rounded-md">
                  <span className="text-[10px] font-mono uppercase text-mono-500 font-bold block mb-1">
                    Guiding Problem-Solving Prompt:
                  </span>
                  <p className="text-xs font-semibold text-mono-900 italic">
                    "{aiOutput.guidingQuestion}"
                  </p>
                </div>
              )}

              {aiOutput.suggestedDocs && aiOutput.suggestedDocs.length > 0 && (
                <div className="space-y-1.5 pt-2">
                  <span className="text-[10px] font-mono uppercase text-mono-500 font-bold block">
                    Recommended Reading & Reference Materials:
                  </span>
                  <div className="space-y-1">
                    {aiOutput.suggestedDocs.map((doc, i) => (
                      <div key={i} className="flex items-center gap-2 text-xs text-mono-800 bg-white px-3 py-1.5 rounded border border-mono-200">
                        <BookOpen className="w-3.5 h-3.5 text-mono-600 shrink-0" />
                        <span className="truncate">{doc}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Guardrail Policy Disclaimer */}
          <div className="p-3 border border-mono-200 rounded-md bg-mono-100 text-[11px] text-mono-600 flex items-start gap-2">
            <Lock className="w-4 h-4 text-mono-800 shrink-0 mt-0.5" />
            <div>
              <span className="font-bold text-mono-900 block">System Integrity Policy</span>
              SkillLoop automatically redacts raw solution code, direct copy-paste snippets, and complete challenge implementations. Humans must build, defend, and adapt solutions.
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-mono-200 bg-white flex justify-between items-center">
          <span className="text-xs text-mono-500 font-mono">AI Capability Assistant Active</span>
          <button
            onClick={onClose}
            className="px-4 py-2 bg-mono-950 text-white text-xs font-semibold rounded-md hover:bg-mono-800 transition-colors"
          >
            Back to Workspace
          </button>
        </div>
      </div>
    </div>
  );
};
